name: Build & push Docker image

on:
  schedule:
    - cron:  '30 7 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get /HolismHolding/Infra
        run: |
          sudo mkdir /HolismHolding
          sudo chmod -R 777 /HolismHolding
          cd /HolismHolding
          git clone https://github.com/HolismHolding/Infra

      - name: Get Sultanimmubin/Path using actions/checkout@v2
        uses: actions/checkout@v2
        with:
          repository: Sultanimmubin/Path
          token: ${{ github.token }}
          path: Sultanimmubin/Path

      - name: Copy Sultanimmubin/Path to root
        run: |
          sudo mkdir /Sultanimmubin
          sudo chmod -R 777 /Sultanimmubin
          cp -r $GITHUB_WORKSPACE/Sultanimmubin/Path /Sultanimmubin/Path

      - name: Build production docker
        run: |
          cd /Sultanimmubin/Path
          /HolismHolding/Infra/Commands/Build

      - name: Log in to GitHub Container Repository
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push the image
        run: |
          docker push ghcr.io/sultanimmubin/path:latest